### ISSUE TITLE
Build vocab from tokenized corpus, i.e. List[List[str]]

### ISSUE THREAD

**Issue by pietrolesci** [Kaleidophon/token2index#4]
**Describe the solution you'd like**
Allow the `T2I.build` method to accept List[List[str]].

Example:
```python
tokenized_corpus = [
    ["This", "is", "a", "sentence"],
    ["This", "is", "another", "sentence"]
]
T2I.build(tokenized_corpus)
```

Currently it can be implemented as follows, but it would be nice to have it supported automatically:
```python
# flatten List[List[str]] with a generator to avoid memory usage
gen = (i for sent in tokenized_corpus for i in sent)
T2I.build(gen)
```

**Comment by Kaleidophon** [comment]
Thank you, I think this seems like a useful feature to add! I assume that you already tokenized the sentence with another tool in order to obtain the sentence in the `List[List[str]]` form?

**Comment by pietrolesci** [comment]
Yes, often one wants to clean the text first and the n build a vocabulary. That is why I think this feature is very useful



________________________________
Da: Kaleidophon <notifications@github.com>
Inviato: Tuesday, October 27, 2020 8:49:46 AM
A: Kaleidophon/token2index <token2index@noreply.github.com>
Cc: Lesci, Pietro <Pietro.Lesci@Bain.com>; Author <author@noreply.github.com>
Oggetto: Re: [Kaleidophon/token2index] Build vocab from tokenized corpus, i.e. List[List[str]] (#4)


Thank you, I think this seems like a useful feature to add! I assume that you already tokenized the sentence with another tool in order to obtain the sentence in the List[List[str]] form?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Kaleidophon_token2index_issues_4-23issuecomment-2D717055259&d=DwMCaQ&c=YgvAunA6A5zFF9cMHqSY3cSQ3MG-auFOlwIB7e1Llto&r=KJcyjd1_LgakxC4ejFYNh6EZaha4AyEmSsAX6L2Vw5o&m=j7RuhkKa2mrOitxIzS7tiZe0uVFpj3xNmRfpZ_rVCWU&s=GQFaN44oTVxFh_Xja-T55Y_UajvvPu1v4L2eTC8n2Xc&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AOXDLLNM2GHZKX6OE63HAF3SMZ3RVANCNFSM4S7XW4CQ&d=DwMCaQ&c=YgvAunA6A5zFF9cMHqSY3cSQ3MG-auFOlwIB7e1Llto&r=KJcyjd1_LgakxC4ejFYNh6EZaha4AyEmSsAX6L2Vw5o&m=j7RuhkKa2mrOitxIzS7tiZe0uVFpj3xNmRfpZ_rVCWU&s=Gwv6j0JjNXF-lAnXn3ATlIQn8MZeTqgYJHtAlSB3efM&e=>.

________________________________
This e-mail, including any attachments, contains confidential information of Bain & Company, Inc. ("Bain") and/or its clients. It may be read, copied and used only by the intended recipient. Any use by a person other than its intended recipient, or by the recipient but for purposes other than the intended purpose, is strictly prohibited. If you received this e-mail in error, please contact the sender and then destroy this e-mail. Opinions, conclusions and other information in this message that do not relate to the official business of Bain shall be understood to be neither given nor endorsed by Bain. Any personal information sent over e-mail to Bain will be processed in accordance with our Privacy Policy (https://www.bain.com/privacy).

**Comment by Kaleidophon** [comment]
I added the feature and new tests, the new version of the package (1.0.2) is available via pip now!
